package org.jbpm.examples.purchases;

/**
 * This class was automatically generated by the data modeler tool.
 */
@org.kie.workbench.common.services.datamodeller.annotations.Label(value = "Purchase Order")
public class PurchaseOrder  implements java.io.Serializable {

static final long serialVersionUID = 1L;
    
    @org.kie.workbench.common.services.datamodeller.annotations.Label(value = "Description")
    private java.lang.String description;
    
    @org.kie.workbench.common.services.datamodeller.annotations.Label(value = "Lines")
    private java.util.List<org.jbpm.examples.purchases.PurchaseOrderLine> lines;
    
    @org.kie.workbench.common.services.datamodeller.annotations.Label(value = "Header")
    private org.jbpm.examples.purchases.PurchaseOrderHeader header;

    public PurchaseOrder() {

    }
    
    public java.lang.String getDescription() {
        return this.description;
    }

    public void setDescription(  java.lang.String description ) {
        this.description = description;
    }
    
    public java.util.List<org.jbpm.examples.purchases.PurchaseOrderLine> getLines() {
        return this.lines;
    }

    public void setLines(  java.util.List<org.jbpm.examples.purchases.PurchaseOrderLine> lines ) {
        this.lines = lines;
    }
    
    public org.jbpm.examples.purchases.PurchaseOrderHeader getHeader() {
        return this.header;
    }

    public void setHeader(  org.jbpm.examples.purchases.PurchaseOrderHeader header ) {
        this.header = header;
    }




}